# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: hoopoelang

builds:
  - id: hclfmt
    main: ./cmd/hclfmt
    binary: hclfmt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hoopoelabs/hoopoelang/version.Version={{.Tag}}

  - id: hcldec
    main: ./cmd/hcldec
    binary: hcldec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hoopoelabs/hoopoelang/version.Version={{.Tag}}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: hoopoelabs
    name: hoopoelang
